### ISSUE TITLE
Cannot install on Python 3.10.6 on ubuntu-22.04

### ISSUE THREAD

**Issue by SachidanandAlle** [masadcv/numpymaxflow#16]
https://github.com/masadcv/numpymaxflow/blob/0ec14eb6d6656e07abbdeafe8abd9859c3239ebb/.github/workflows/build-whl-publish.yml#L91

**Comment by SachidanandAlle** [comment]
Sorry.. i didn't see latest version already pushed to pip.. using 0.0.5 works..

**Comment by masadcv** [comment]
Yes, I was going to let you know. Latest version has 3.10 support and additional features to improve accuracy of maxflow.
